export const schemaSql = `
CREATE TABLE IF NOT EXISTS comprovei_importacoes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ws VARCHAR(10) NOT NULL,
  data_inicial DATE NOT NULL,
  data_final DATE NOT NULL,
  status ENUM('iniciado','sucesso','erro') NOT NULL DEFAULT 'iniciado',
  total_linhas INT NOT NULL DEFAULT 0,
  total_inseridas INT NOT NULL DEFAULT 0,
  mensagem TEXT NULL,
  url_arquivo TEXT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finalizado_em DATETIME NULL,
  INDEX idx_ws_periodo (ws, data_inicial, data_final),
  INDEX idx_criado_em (criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comprovei_ws601_rotas (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hash_linha CHAR(64) NOT NULL,
  data_inicial_importacao DATE NOT NULL,
  data_final_importacao DATE NOT NULL,
  data_importacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_rota DATE NULL,
  rota_roteiro VARCHAR(255) NULL,
  motorista VARCHAR(255) NULL,
  codigo_motorista VARCHAR(100) NULL,
  placa VARCHAR(50) NULL,
  status_rota VARCHAR(100) NULL,
  qtd_paradas DECIMAL(18,4) NULL,
  qtd_documentos DECIMAL(18,4) NULL,
  qtd_volumes DECIMAL(18,4) NULL,
  transportadora VARCHAR(255) NULL,
  base_origem VARCHAR(255) NULL,
  base_destino VARCHAR(255) NULL,
  dados_json JSON NOT NULL,
  UNIQUE KEY uk_ws601_hash (hash_linha),
  INDEX idx_data_rota (data_rota),
  INDEX idx_rota (rota_roteiro),
  INDEX idx_placa (placa),
  INDEX idx_importacao (data_importacao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comprovei_ws613_documentos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hash_linha CHAR(64) NOT NULL,
  data_inicial_importacao DATE NOT NULL,
  data_final_importacao DATE NOT NULL,
  data_importacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  documento VARCHAR(255) NULL,
  chave VARCHAR(80) NULL,
  emissao DATE NULL,
  embarcador VARCHAR(255) NULL,
  cnpj_embarcador VARCHAR(30) NULL,
  cliente VARCHAR(255) NULL,
  cidade_destino VARCHAR(255) NULL,
  uf_destino VARCHAR(10) NULL,
  status_documento VARCHAR(100) NULL,
  ultima_ocorrencia VARCHAR(255) NULL,
  data_finalizacao DATE NULL,
  rota_roteiro VARCHAR(255) NULL,
  motorista VARCHAR(255) NULL,
  placa VARCHAR(50) NULL,
  data_rota DATE NULL,
  valor DECIMAL(18,4) NULL,
  volume DECIMAL(18,4) NULL,
  qtd_volumes DECIMAL(18,4) NULL,
  pedido VARCHAR(255) NULL,
  remessa VARCHAR(255) NULL,
  dados_json JSON NOT NULL,
  UNIQUE KEY uk_ws613_hash (hash_linha),
  INDEX idx_documento (documento),
  INDEX idx_chave (chave),
  INDEX idx_data_rota (data_rota),
  INDEX idx_emissao (emissao),
  INDEX idx_importacao (data_importacao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;
